// sample/src/App.tsx
import './App.css'
import { VibrationButton } from './components/VibrationButton/index.tsx'

function App() {
  return (
    <main>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite-deno.svg" className="logo" alt="Vite logo" />
        </a>
      </div>
      <h1>Vite + React</h1>

      <VibrationButton />

      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </main>
  )
}

export default App

// sample/vite-vue/src/App.vue
<script setup lang="ts">
import HapticButton from "./components/HapticButton/index.vue"
</script>

<template>
    <div>
        <a href="https://vite.dev" target="_blank">
            <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://vuejs.org/" target="_blank">
            <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
        </a>
    </div>
    <h1>Vite + Vue</h1>

    <HapticButton />

    <p class="read-the-docs">
        Click on the Vite and Vue logos to learn more
    </p>
</template>

<style scoped>
.logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
}
.logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
    filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
